name: update_application
description: A cross-platform Flutter plugin for in-app updates on Android & iOS.
version: 0.0.2
homepage: https://github.com/midhlajnazar/update_application
repository: https://github.com/midhlajnazar/update_application
issue_tracker: https://github.com/midhlajnazar/update_application/issues
documentation: https://github.com/midhlajnazar/update_application#readme

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
flutter: 
  plugin:
    platforms:
      android:
        package: com.mjnaz.fi.ae.update_application
        pluginClass: UpdateApplicationPlugin
      ios:
        pluginClass: UpdateApplicationPlugin

 